include:
  - component: $CI_SERVER_FQDN/components/markdownlint/markdownlint@2.1.0
    inputs:
      image: davidanson/markdownlint-cli2:v0.20.0@sha256:8f7487027e6786a583da1c8be8b0541bbd17582a4b8fbe3e27a29d9f29fa77d0
